export interface EditorCreateOptions {
  readonly columnToReveal?: number
  readonly completionTriggerCharacters: any
  readonly content: string
  readonly diagnosticsEnabled: boolean
  readonly fontFamily: string
  readonly fontSize: number
  readonly fontWeight: number
  readonly formatOnSave: boolean
  readonly height: number
  readonly hoverEnabled: boolean
  readonly id: number
  readonly isAutoClosingBracketsEnabled: boolean
  readonly isAutoClosingQuotesEnabled: boolean
  readonly isAutoClosingTagsEnabled: boolean
  readonly isMonospaceFont: boolean
  readonly isQuickSuggestionsEnabled: boolean
  readonly languageId: string
  readonly letterSpacing: number
  readonly lineNumbers: boolean
  readonly lineToReveal?: number
  readonly links: any
  readonly rowHeight: number
  readonly savedDeltaY: number
  readonly savedSelections: any
  readonly tabSize: number
  readonly uri: string
  readonly width: number
  readonly x: number
  readonly y: number
}
