export const keep = [
  // 'ColorPicker.handleSliderPointerDown',
  // 'ColorPicker.handleSliderPointerMove',
  // 'ColorPicker.loadContent',
  'Editor.create',
  'Editor.getWordAt',
  'Editor.getWordBefore',
  'Editor.offsetAt',
  'Editor.render',
  'Editor.getKeyBindings',
  'Editor.getQuickPickMenuEntries',
  // 'ColorPicker.render',
  'Editor.getText',
  'Editor.getSelections',
  'Font.ensure',
  'Hover.getHoverInfo',
  'Hover.handleSashPointerDown',
  'Hover.handleSashPointerMove',
  'Hover.handleSashPointerUp',
  'Hover.loadContent',
  'Hover.render',
  'Initialize.initialize',
]
