export const keep = [
  'ActivateByEvent.activateByEvent',
  'ExtensionHostManagement.activateByEvent',
  'Editor.applyEdit2',
  'Editor.applyEdits2',
  'Editor.closeFind2',
  'Editor.closeWidget2',
  'Editor.create',
  'Editor.getKeyBindings',
  'Editor.getSourceActions',
  'Editor.getLines2',
  'Editor.getPositionAtCursor',
  'Editor.getOffsetAtCursor',
  'Editor.getQuickPickMenuEntries',
  'Editor.getSelections',
  'Editor.hotReload',
  'Editor.getSelections2',
  'Editor.getDiagnostics',
  'Editor.getText',
  'Editor.getWordAt',
  'Editor.getWordAt2',
  'Editor.getWordAtOffset2',
  'Editor.getUri',
  'Editor.getWordBefore',
  'Editor.getWordBefore2',
  'Editor.offsetAt',
  'Editor.render',
  'Editor.setSelections2',
  'Editor.updateDebugInfo',
  'Editor.getLanguageId',
  'Editor.getProblems',
  'Editor.getKeys',
  'Editor.getMenuIds',
  'Editor.getMenuEntries',
  'Editor.getMenuEntries2',
  'Font.ensure',
  'HandleMessagePort.handleMessagePort',
  'Hover.getHoverInfo',
  'Hover.handleSashPointerDown',
  'Hover.handleSashPointerMove',
  'Hover.handleSashPointerUp',
  'Hover.loadContent',
  'Hover.render',
  'Initialize.initialize',
  'SendMessagePortToExtensionHostWorker.sendMessagePortToExtensionHostWorker',
  // 'ColorPicker.handleSliderPointerDown',
  // 'ColorPicker.handleSliderPointerMove',
  // 'ColorPicker.loadContent',
  // 'ColorPicker.render',
]
