export const SetBounds = 'setBounds'
export const SetColor = 'setColor'
export const SetContentHeight = 'setContentHeight'
export const SetNegativeMargin = 'setNegativeMargin'
export const SetOffsetX = 'setOffsetX'
export const SetScrollBar = 'setScrollBar'
export const SetValue = 'setValue'
export const SetDom2 = 'Viewlet.setDom2'
