import type { EditorState } from '../State/State.ts'
import * as Assert from '../Assert/Assert.ts'
import * as EditorStates from '../EditorStates/EditorStates.ts'
import { emptyIncrementalEdits } from '../EmptyIncrementalEdits/EmptyIncrementalEdits.ts'
import * as FocusKey from '../FocusKey/FocusKey.ts'

export const createEditor2 = (
  id: number,
  uri: string,
  x: number,
  y: number,
  width: number,
  height: number,
  platform: number,
  assetDir: string,
): void => {
  Assert.number(id)
  const editor: EditorState = {
    additionalFocus: 0,
    assetDir,
    charWidth: 0,
    columnWidth: 0,
    completionState: '',
    completionTriggerCharacters: [],
    completionUid: 0,
    cursorWidth: 2,
    debugEnabled: false,
    decorations: [],
    deltaX: 0,
    deltaY: 0,
    diagnostics: [],
    diagnosticsEnabled: false,
    differences: [],
    embeds: [],
    finalDeltaY: 0,
    finalY: 0,
    focus: 0,
    focused: false,
    focusKey: FocusKey.Empty,
    fontFamily: '',
    fontSize: 0,
    fontWeight: 0,
    handleOffsetX: 0,
    height,
    highlightedLine: -1,
    id,
    incrementalEdits: emptyIncrementalEdits,
    initial: true,
    invalidStartIndex: 0,
    isAutoClosingBracketsEnabled: false,
    isAutoClosingQuotesEnabled: false,
    isAutoClosingTagsEnabled: false,
    isMonospaceFont: false,
    isQuickSuggestionsEnabled: false,
    itemHeight: 20,
    languageId: '',
    letterSpacing: 0,
    lineCache: [],
    lineNumbers: false,
    lines: [],
    longestLineWidth: 0,
    maxLineY: 0,
    minimumSliderSize: 20,
    minLineY: 0,
    modified: false,
    numberOfLines: 0,
    numberOfVisibleLines: 0,
    platform,
    primarySelectionIndex: 0,
    rowHeight: 0,
    savedSelections: [],
    scrollBarHeight: 0,
    scrollBarWidth: 0,
    selections: new Uint32Array(),
    tabSize: 0,
    textInfos: [],
    tokenizerId: 0,
    uid: id,
    undoStack: [],
    uri,
    validLines: [],
    visualDecorations: [],
    widgets: [],
    width,
    x,
    y,
  }
  EditorStates.set(id, editor, editor)
}
