import * as EditorPreferences from '../EditorPreferences/EditorPreferences.ts'
import * as Preferences from '../Preferences/Preferences.ts'

export const getEditorPreferences = async () => {
  const [
    diagnosticsEnabled,
    fontFamily,
    fontSize,
    fontWeight,
    formatOnSave,
    hoverEnabled,
    isAutoClosingBracketsEnabled,
    isAutoClosingQuotesEnabled,
    isAutoClosingTagsEnabled,
    isQuickSuggestionsEnabled,
    lineNumbers,
    highlightActiveLineNumber,
    rowHeight,
    tabSize,
    letterSpacing,
    completionTriggerCharacters,
    minimapEnabled,
    mergeConflictActionsEnabled,
    breadcrumbsEnabled,
    insertSpaces,
    dragAndDropEnabled,
    roundedSelection,
    combineWhitespaceTokens,
  ] = await Promise.all([
    EditorPreferences.diagnosticsEnabled(),
    EditorPreferences.getFontFamily(),
    EditorPreferences.getFontSize(),
    EditorPreferences.getFontWeight(),
    EditorPreferences.getFormatOnSave(),
    EditorPreferences.getHoverEnabled(),
    EditorPreferences.isAutoClosingBracketsEnabled(),
    EditorPreferences.isAutoClosingQuotesEnabled(),
    EditorPreferences.isAutoClosingTagsEnabled(),
    EditorPreferences.isQuickSuggestionsEnabled(),
    EditorPreferences.getLineNumbers(),
    EditorPreferences.getHighlightActiveLineNumber(),
    EditorPreferences.getRowHeight(),
    EditorPreferences.getTabSize(),
    EditorPreferences.getLetterSpacing(),
    EditorPreferences.getCompletionTriggerCharacters(),
    EditorPreferences.getMinimapEnabled(),
    EditorPreferences.getMergeConflictActionsEnabled(),
    EditorPreferences.getBreadcrumbsEnabled(),
    EditorPreferences.getInsertSpaces(),
    EditorPreferences.getDragAndDropEnabled(),
    EditorPreferences.getRoundedSelection(),
    Preferences.get('editor.combineWhitespaceTokens'),
  ])
  return {
    breadcrumbsEnabled,
    combineWhitespaceTokens: combineWhitespaceTokens ?? false,
    completionTriggerCharacters,
    diagnosticsEnabled,
    dragAndDropEnabled,
    fontFamily,
    fontSize,
    fontWeight,
    formatOnSave,
    highlightActiveLineNumber,
    hoverEnabled,
    insertSpaces,
    isAutoClosingBracketsEnabled,
    isAutoClosingQuotesEnabled,
    isAutoClosingTagsEnabled,
    isQuickSuggestionsEnabled,
    letterSpacing,
    lineNumbers,
    mergeConflictActionsEnabled,
    minimapEnabled,
    roundedSelection,
    rowHeight,
    tabSize,
  }
}
