export const Link = 'Link'
export const EditorGoToDefinitionLink = 'EditorGoToDefinitionLink'
export const EditorRenameHighlight = 'EditorRenameHighlight'
export const Function = 'Function'
export const Parameter = 'Parameter'
export const Type = 'Type'
export const VariableName = 'VariableName'
export const Class = 'Class'
