export const HandlePointerDown = 'handlePointerDown'
export const HandleSashPointerDown = 'handleSashPointerDown'
export const HandleClose = 'handleClose'
export const HandleFocusIn = 'handleFocusIn'
export const HandleClick = 'handleClick'
export const HandleInput = 'handleInput'
export const HandleFocus = 'handleFocus'
