export const HandlePointerDown = 'handlePointerDown'
export const HandleSashPointerDown = 'handleSashPointerDown'
export const HandleClose = 'handleClose'
export const HandleFocusIn = 'handleFocusIn'
export const HandleClick = 'handleClick'
