import * as AssetDir from '../AssetDir/AssetDir.ts'

export const Add = 'Add'
export const ArrowDown = 'ArrowDown'
export const ArrowUp = 'ArrowUp'
export const Blank = 'Blank'
export const ClearAll = 'ClearAll'
export const Close = 'Close'
export const Cloud = 'Cloud'
export const CollapseAll = 'CollapseAll'
export const DebugAlt2 = 'DebugAlt2'
export const Edit = 'Edit'
export const Ellipsis = 'Ellipsis'
export const Extensions = 'Extensions'
export const Files = 'Files'
export const None = ''
export const RecordKey = 'RecordKey'
export const Refresh = 'Refresh'
export const Replace = 'Replace'
export const ReplaceAll = 'ReplaceAll'
export const Search = 'Search'
export const SettingsGear = 'SettingsGear'
export const SourceControl = 'SourceControl'
export const SplitHorizontal = 'SplitHorizontal'
export const Tag = 'Tag'
export const Trash = 'Trash'
