export const keep = [
  'ColorPicker.handleSliderPointerDown',
  'ColorPicker.handleSliderPointerMove',
  'ColorPicker.loadContent',
  'Editor.create',
  'Editor.getWordAt',
  'Editor.getWordBefore',
  'Editor.offsetAt',
  'Editor.render',
  'ColorPicker.render',
  'Editor.getText',
  'Editor.getSelections',
  // 'EditorCompletion.advance',
  // 'EditorCompletion.handleEditorBlur',
  // 'EditorCompletion.handleEditorClick',
  // 'EditorCompletion.handleEditorDeleteLeft',
  // 'EditorCompletion.handleEditorType',
  // 'EditorCompletion.loadContent',
  // 'EditorCompletion.selectCurrent',
  // 'EditorCompletion.selectIndex',
  'FindWidget.focusFirst',
  'FindWidget.focusIndex',
  'FindWidget.focusLast',
  'FindWidget.focusNext',
  'FindWidget.focusPrevious',
  'FindWidget.handleInput',
  'FindWidget.loadContent',
  'Font.ensure',
  'Hover.getHoverInfo',
  'Hover.handleSashPointerDown',
  'Hover.handleSashPointerMove',
  'Hover.handleSashPointerUp',
  'Hover.loadContent',
  'Hover.render',
  'Initialize.initialize',
]
