import type { EditorState } from '../State/State.ts'
import { emptyIncrementalEdits } from '../EmptyIncrementalEdits/EmptyIncrementalEdits.ts'

export const emptyEditor = {
  bracketMatchInfos: [],
  breadcrumbsEnabled: false,
  breakPoints: [],
  cursorInfos: [],
  debugEnabled: false,
  decorations: [],
  deltaX: 0,
  deltaY: 0,
  diagnostics: [],
  differences: [],
  documentSymbols: [],
  dragAndDropEnabled: true,
  embeds: [],
  endOfLine: 'lf',
  endOfLineDecorations: [],
  focused: false,
  foldingRanges: [],
  gutterDecorations: [],
  hasListener: false,
  height: 0,
  highlightedLine: -1,
  incrementalEdits: emptyIncrementalEdits,
  insertSpaces: true,
  isSelecting: false,
  languageId: '', // TODO use numeric language id?
  lineCache: [],
  lines: [],
  longestLineWidth: 0,
  maxLineY: 0,
  mergeConflictActionsEnabled: false,
  mergeConflicts: [],
  minimapEnabled: false,
  minimapLines: [],
  minimapRevision: 0,
  minLineY: 0,
  outerHeight: 0,
  outerWidth: 0,
  redoStack: [],
  scrollBarHeight: 0,
  selectionAnchorPosition: {
    columnIndex: 0,
    rowIndex: 0,
  },
  selectionAutoMovePosition: {
    x: 0,
    y: 0,
  },
  selectionInfos: [],
  selections: new Uint32Array(),
  textDragDropPosition: {
    columnIndex: 0,
    rowIndex: 0,
  },
  textDragId: 0,
  textInfos: [],
  tokenizerId: 0,
  undoStack: [],
  uri: '',
  viewLineIndices: [],
  visibleLineIndices: [],
  visibleViewLineIndices: [],
  width: 0,
  workspaceUri: '',
  x: 0,
  y: 0,
} satisfies Partial<EditorState> as unknown as EditorState
