import { emptyIncrementalEdits } from '../EmptyIncrementalEdits/EmptyIncrementalEdits.ts'

export const emptyEditor = {
  debugEnabled: false,
  decorations: [],
  deltaX: 0,
  deltaY: 0,
  diagnostics: [],
  differences: [],
  embeds: [],
  focused: false,
  height: 0,
  highlightedLine: -1,
  incrementalEdits: emptyIncrementalEdits,
  languageId: '', // TODO use numeric language id?
  lineCache: [],
  lines: [],
  longestLineWidth: 0,
  maxLineY: 0,
  minLineY: 0,
  scrollBarHeight: 0,
  selections: new Uint32Array(),
  textInfos: [],
  tokenizerId: 0,
  undoStack: [],
  uri: '',
  width: 0,
  x: 0,
  y: 0,
}
