import type { EditorState } from '../State/State.ts'
import { emptyIncrementalEdits } from '../EmptyIncrementalEdits/EmptyIncrementalEdits.ts'

export const emptyEditor: EditorState = {
  additionalFocus: 0,
  assetDir: '',
  charWidth: 0,
  columnWidth: 0,
  completionState: '',
  completionTriggerCharacters: [],
  completionUid: 0,
  cursorInfos: [],
  cursorWidth: 0,
  debugEnabled: false,
  decorations: [],
  deltaX: 0,
  deltaY: 0,
  diagnostics: [],
  diagnosticsEnabled: false,
  differences: [],
  embeds: [],
  finalDeltaY: 0,
  finalY: 0,
  focus: 0,
  focused: false,
  focusKey: 0,
  fontFamily: '',
  fontSize: 0,
  fontWeight: 0,
  handleOffset: 0,
  handleOffsetX: 0,
  hasListener: false,
  height: 0,
  highlightedLine: -1,
  id: 0,
  incrementalEdits: emptyIncrementalEdits,
  initial: false,
  invalidStartIndex: 0,
  isAutoClosingBracketsEnabled: false,
  isAutoClosingQuotesEnabled: false,
  isAutoClosingTagsEnabled: false,
  isMonospaceFont: false,
  isQuickSuggestionsEnabled: false,
  isSelecting: false,
  itemHeight: 0,
  languageId: '', // TODO use numeric language id?
  letterSpacing: 0,
  lineCache: [],
  lineNumbers: false,
  lines: [],
  longestLineWidth: 0,
  maxLineY: 0,
  minimumSliderSize: 0,
  minLineY: 0,
  modified: false,
  numberOfLines: 0,
  numberOfVisibleLines: 0,
  platform: 0,
  primarySelectionIndex: 0,
  redoStack: [],
  rowHeight: 0,
  savedSelections: [],
  scrollBarHeight: 0,
  scrollBarWidth: 0,
  selectionAnchorPosition: {
    columnIndex: 0,
    rowIndex: 0,
  },
  selectionAutoMovePosition: {
    columnIndex: 0,
    rowIndex: 0,
  },
  selectionInfos: [],
  selections: new Uint32Array(),
  tabSize: 0,
  textInfos: [],
  tokenizerId: 0,
  uid: 0,
  undoStack: [],
  uri: '',
  validLines: [],
  visualDecorations: [],
  widgets: [],
  width: 0,
  x: 0,
  y: 0,
}
